export enum RcaStep {
  NON_VENDOR_SPEND = 'NON_VENDOR_SPEND',
  FINANCE_ADJUSTMENT_DELTA = 'FINANCE_ADJUSTMENT_DELTA',
  MISC_BILLABLE_ROLE = 'MISC_BILLABLE_ROLE',
  RESIDUAL_GAP = 'RESIDUAL_GAP',
  FED_ESTIMATED_VS_ACTUAL = 'FED_ESTIMATED_VS_ACTUAL',
  CROSS_BU_ATTRIBUTION = 'CROSS_BU_ATTRIBUTION',
  EXCHANGE_RATE_IMPACT = 'EXCHANGE_RATE_IMPACT',
}

export const RCA_STEP_ORDER: Record<RcaStep, number> = {
  [RcaStep.NON_VENDOR_SPEND]: 1,
  [RcaStep.FINANCE_ADJUSTMENT_DELTA]: 2,
  [RcaStep.MISC_BILLABLE_ROLE]: 3,
  [RcaStep.RESIDUAL_GAP]: 4,
  [RcaStep.FED_ESTIMATED_VS_ACTUAL]: 5,
  [RcaStep.CROSS_BU_ATTRIBUTION]: 6,
  [RcaStep.EXCHANGE_RATE_IMPACT]: 7,
};
